### PR TITLE
re-added TURBO changes in a hopefully more proper way

### PR DESCRIPTION
**Pull request by rstrausb**
I think I have added the necessary TURBO things while not getting rid of any of the things that were already there.

### CODE REVIEW

**Comment by rstrausb** [comment]
@mcoughlin @Theodlz Here is the new branch with the hopefully cleaner addition of TURBO things.  I tried running it locally, and I get a key error that I wasn't getting before: test_alert_broker_TURBO.py:75: KeyError.  Other than that it seems to be running fine.  Let me know if this looks better.

**Comment by mcoughlin** [comment]
@rstrausb please fix the linting.

**Comment by rstrausb** [comment]
@mcoughlin If its just the unused import of pprint I have removed that and pushed that change.

**Comment by mcoughlin** [comment]
@rstrausb You should do

pre-commit install
pre-commit run --files file/complained/about

This is what we use to keep our code uniform and readable.

**Comment by mcoughlin** [comment]
@rstrausb As for the rest of the tests, I think you may have forgotten to copy the WNTR filter in the default config to be the same as for TURBO.

**Comment by Theodlz** [comment]
Hi @rstrausb. I'm in the process of reviewing your PR. I'm having some trouble running the code as Kowalski's dependencies aren't up to date, which is a blocker on certain configs.
I have this PR open and almost ready to go in, that will add a lot of changes to Kowalski, which all facilitate the development cycle of the app, and makes it easier to add new things: https://github.com/skyportal/kowalski/pull/186

When it goes in, it will probably create some merge conflicts with your current PR, but any of the changes you made will be facilitated. If you give me the right access to your fork, I'll be happy to solve whatever merge conflicts occur, so that we can get your changes in Kowalski reasonably quickly.

Could you please pull the branch from that PR and try to run it to see if it works well for you? Are you working on MacOS or linux by the way?

**Comment by Theodlz** [comment]
Hi @mcoughlin, on it.

**Comment by Theodlz** [comment]
Hi @rstrausb, I commited a bunch of changes to match the changes from the last PR that was merged with main. However, I am having a problem with the ingester tests. All the avro files that you ingested apparently have the same `candid` (or at least that's what the code says)? Since that's what it's indexed on, it can't really ingest more than one and the tests fail. Can you make sure that each alert have a distinct `candid`?

**Comment by rstrausb** [comment]
@Theodlz I'm working on it, but it might take a little while I'm on a break this week.  If you need to move things forward, you can temporarily remove the alerts while I work on fixing them.

**Comment by Theodlz** [comment]
> @Theodlz I'm working on it, but it might take a little while I'm on a break this week. If you need to move things forward, you can temporarily remove the alerts while I work on fixing them.

Otherwise, if you are fine with that, I can just keep those files and edit them to make sure they have unique `candid` values?

**Comment by rstrausb** [comment]
@Theodlz That sounds like a good temporary fix, thanks!

**Review by mcoughlin — APPROVED** [review]
Thanks @rstrausb and @Theodlz. LGTM.

**Pull request merged**
