### PR TITLE
changes made to add TURBO to kowalski

### PR DESCRIPTION
**Pull request by rstrausb**

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @rstrausb, this is already better. However, there are a lot of changes I don't understand. In a lot of files you modified, instead of creating new components (or entries in the config) for TURBO, you replace, and even sometimes remove existing things. Like in the config you replace a lot of winter code by turbo, switch ZTF and pgir, ...

I am not sure that is what you want. If so, please explain why in your PR's description. 

Also, there are some changes that are just not necessary, like: removed spaces, modified indentations, added spaces, removed some logs... These need to be canceled (except the indentation if justified).

In general it would be good to provide some context in a PR's description. Otherwise, it's a little hard for the reviewer to know what the code is supposed to do.

**Comment by Theodlz** [comment]
@mcoughlin can you allow @rstrausb's GitHub actions to run? I'm not a maintainer of the repo so I can't do it myself.

**Comment by mcoughlin** [comment]
@Theodlz I clicked the button!

**Comment by rstrausb** [comment]
@Theodlz @mcoughlin I'm going to make a new pull and make only the changes I needed to add TURBO.  I'll let you all know when that is done.

**Comment by Theodlz** [comment]
That sounds great. Let me know if you need any help with that.

**Pull request closed without merging**
